### ISSUE TITLE
Cannot install via Cocoapods when using Swift

### ISSUE THREAD

**Issue by TimothyChilvers** [segment-integrations/analytics-ios-integration-optimizely#11]
Cocoapods gives the error: `target has transitive dependencies that include static binaries: (/Users/timothychilvers/Documents/Lovecrafts-iOS/Pods/Optimizely-iOS-SDK/Optimizely.framework)` on `pod install`

**Comment by ladanazita** [comment]
Hi @TimothyChilvers,

Sorry for the delay here.
This unfortunately is a [common issue](https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/3#issuecomment-180460608) that doesn't have an out of the box solution due to [Cocoapods and static libraries](https://github.com/CocoaPods/CocoaPods/issues/2926) not working well together.

The only solution is  to copy the [integration code](https://github.com/segment-integrations/analytics-ios-integration-optimizely/tree/master/Pod/Classes) manually into your project, then depend on Optimizley directly. This eliminates the transitive dependency (from App -> Segment-Optimizely -> Optimizely to App -> Optimizely).

Moving forward, we recommend using [Optimizely-X](https://github.com/segment-integrations/analytics-ios-integration-optimizely-x) as it is the recommended product from Optimizely. 

Best of luck, and please let me know if I can help out further!
Ladan
